
module.exports = async (client, interaction, args) => {

    const user = interaction.options.getUser('user');

    if (!user) return client.errUsage({ usage: "hug [mention user]", type: 'editreply' }, interaction);

    var kills = [
        ` egy hosszú nap után lehuppan a kanapéra ${user} mellé, és bekapcsolja az Agymenőket. Egy Sheldon Cooper vicc után ${user} annyira nevet, hogy belehal.`,
        `${interaction.user} Alt+F4-et nyomott ${user}.exe-n!`,
        `${interaction.user} megpróbált fuvolázni, és felrobbantotta ${user} fejét.`,
        `${interaction.user} kirobbantotta a dobhártyáját, mert túl hangosan hallgatott zenét.`,
        `${interaction.user} halálos ökölharcra hívja ki ${user}-t. ${user} nyer.`,
        `${interaction.user} egy billentyűzettel hasítja ketté ${user} fejét.`,
        `${interaction.user} egy hűtővel zúzza szét ${user}-t.`,
        `${interaction.user} egy karddal fejezi le ${user}-t.`,
        `${interaction.user} túl erősen húzza ${user} fülét, és letépi őket.`,
        `${interaction.user} egy söröshordóban fojtja bele ${user}-t.`,
        `${interaction.user} egy kád forró csokoládéba fojtja ${user}-t. *Milyen volt az utolsó italod?*`,
        `${interaction.user} egy rozsdás vajkéssel belezi ki ${user}-t. Aú!`,
        `${interaction.user} fogkrémmel töltött Oreo-kat etet ${user}-vel, aki állítólag allergiás a fluorra. GGWP.`,
        `${interaction.user} beleszeretett ${user}-be, majd szó szerint összetörte a szívét.`,
        `${interaction.user} egy szuperszonikus fagyasztott pulykát lő ki ${user}-re, azonnal megölve őt.`,
        `${interaction.user} elfelejtette nyitva hagyni az autó ablakát, és ${user} túlmelegedésben hal meg`,
        `${interaction.user} elfelejtette zombibiztossá tenni ${user} kertjét... Úgy tűnik, a zombik jól belaktak tegnap este.`,
        `${interaction.user} rávette ${user}-t, hogy animét nézzen vele. ${user} nem bírta ki.`,
        `${interaction.user} megragadja ${user}-t, betuszkolja egy fagyasztógépbe egy kis gyümölcslével, és 100 Kelvinre állítja a hőmérsékletet, emberi jégkrémet készítve.`,
        `${interaction.user} felbérelt, hogy megöljelek, de nem akarom! ${user}`,
        `${interaction.user} túl erősen öleli meg ${user}-t..`,
        `${interaction.user} Hulk-ként péppé zúzza ${user}-t.`,
        `${interaction.user} megölte ${user}-t azzal, hogy letépte az arcbőrét és maszkot készített belőle.`,
        `${interaction.user} órákig tartó kínzás után öli meg ${user}-t.`,
        `${interaction.user} egy gyertyatartóval öli meg ${user}-t a dolgozószobában`,
        `${interaction.user} kedvességgel öli meg ${user}-t`,
        `${interaction.user} a saját lábával öli meg ${user}-t.`,
        `${interaction.user} egy fejszével gyilkolja meg ${user}-t.`,
        `${interaction.user} megnyomta a delete gombot. Törölte ${user}-t`,
        `${interaction.user} belöki ${user}-t az űr hideg vákuumába.`,
        `${interaction.user} elgázolja ${user}-t egy PT Cruiserrel.`,
        `${interaction.user} fejbe lövi ${user}-t.`,
        `${interaction.user} egy szivárvány lézerrel lő ${user} szájába, aminek hatására ${user} feje szivárványokkal robban fel, és ${user} egyszarvúként születik újjá. :unicorn:`,
        `${interaction.user} lelőtte ${user}-t a Starkiller Bázissal!`,
        `${interaction.user} fehérítőt csempész ${user} limonádéjába.`,
        `${interaction.user} megfojtja ${user}-t.`,
        `${interaction.user} ${user}-t egy interkontinentális rakétához köti, és elküldi vele Észak-Koreába.`,
        `${interaction.user} a halálos átokkal sújt le ${user}-ra... *Avada Kedavra!*`,
        `${interaction.user} egy csók után letépi ${user} ajkait.`,
        `${interaction.user} olyan thicc, hogy összeroppantja ${user} bordáit`,
        `${interaction.user} megpróbál eltalálni egy hordó oldalát, mellé lő, és helyette ${user}-t találja el.`,
        `${interaction.user} bekapcsolja a Rémségek háza (2015-ös film) című filmet a TV-n. ${user}, mivel gyáva, szívrohamban hal meg.`,
        `${interaction.user} annyira menő volt, hogy ${user} belehalt. #Menő`,
        `${interaction.user}, biztos meg akarod ölni ${user}-t? Nekem szimpatikusnak tűnik.`,
        `${user} véletlenül rákattintott egy felugró hirdetésre, amin ez állt: \`Az orvosok utálnak minket, íme a legjobb trükk a meghaláshoz!\``,
        `${user} véletlenül elesett és meghalt, miközben felkelt, hogy megírja a búcsúlevelét.`,
        `${user} evett egy darab egzotikus vajat. Olyan fenomenális volt, hogy belehalt.`,
        `${user} evett egy almát, ami kiderült, hogy viaszból volt. Aznap valaki viaszmérgezésben halt meg.`,
        `${user} túl sok hashajtót vett be, és megfulladt a saját ürülékében. Fúj.`,
        `${user} elvérzett, miközben megpróbált bekerülni a \`Legostobább vidéki pillanatok\` című műsorba.`,
        `${user} vett egy fidget spinnert, és belefulladt a puncikba.`,
        `${user} nem ölhető meg, mert szellem.`,
        `${user} megfullad egy szemetesben.`,
        `${user} megfullad egy csirkecsonton.`,
        `${user} megfullad a Cheerios-on és meghal. Micsoda idióta...`,
        `${user} felteker a zenerendszert, majd rájön, hogy a hangerő már maxon volt, és a Baby szólt Justin Biebertől...`,
        `${user} a szemébe élvez, megvakul, segítségért fut, de egyenesen a vasúti sínekre szalad, és elgázolja egy vonat.`,
        `${user} úgy döntött, jó ötlet megküzdeni egy tigrissel, miközben húsillata van. Nem végződött jól.`,
        `${user} nem csinált elég menő mémet, ezért megkövezték.`,
        `${user} meghalt, miután 50-szer verte le egymás után, szünet nélkül.`,
        `${user} meghalt, miután 90 órán át gamingelt megállás és étkezés nélkül.`,
        `${user} meghalt, miután egy borotvapenge-élű fidget spinnerrel játszott.`,
        `${user} meghalt, miután rájött, milyen szar a nyelvtana`,
        `${user} meghalt, miután megpróbálta túlmémezni a Dank Memert.`,
        `${user} becsületes halált halt. Snoo-snoo általi halál.`,
        `${user} meghalt, mert a RemindMeBot elfelejtette emlékeztetni, hogy lélegezzen`,
        `${user} meghalt, mert elkezdett játszani egy fidget spinnerrel, de rájött, hogy 2016 van, ezért verni kezdte a vén boszorkányra a Hófehérkéből, közben Obama nyírni kezdte a füvüket, ${user} kiugrott az ablakon, és darabokra tépte Obama fűnyírója.`,
        `${user} meghalt, mert ${interaction.user} annyira hülye`,
        `${user} meghalt, mert péntek esti randijára készülve JÓVAL túl sok hot dogot evett.`,
        `${user} meghalt, miközben lejárt szavatosságú, fertőzött nyers halat evett a világ legpiszkosabb rizsével sushiként, közben folyamatosan egy 9 hüvelykes, kevlárt is átszúró szöggel szurkálták a herezacskóját. A szójaszósz macskavizelet volt.`,
        `${user} meghalt a túl magas sóbevitel miatt`,
        `${user} meghalt egy villámgyors agyba rúgástól.`,
        `${user} meghalt egy tragikusan rossz szopás miatt`,
        `${user} meghalt a jeges vödör kihívás közben.`,
        `${user} meghalt, mert túl sok vizet ivott. Hm, szóval mégis lehetséges!.`,
        `${user} meghalt kaktusztüskék evésétől.`,
        `${user} meghalt, mert túl sok segget evett.`,
        `${user} meghalt, mert túl sok kenyeret evett :/`,
        `${user} meghalt ebolában.`,
        `${user} meghalt mém-alulagolás miatt :/`,
        `${user} meghalt, mert nem evett elég segget.`,
        `${user} meghalt, mert nem verte le eléggé. (Van egy egészséges egyensúly, srácok)`,
        `${user} meghalt, mert rossz környéken repostolt`,
        `${user} meghalt, miután 36 órán át folyamatosan kakált.`,
        `${user} meghalt, mert túl gyorsan nyelt le köveket`,
        `${user} meghalt túl sok leégés miatt.`,
        `${user} meghalt, mert túl sokat verte le. (Van egy egészséges egyensúly, srácok)`,
        `${user} meghalt túlszopás miatt`,
        `${user} meghalt egy hidrogénbomba tesztelése közben. Nincs mit eltemetni.`,
        `${user} meghalt, miközben az 'It's Every Day Bro'-t hallgatta`,
        `${user} meghalt, miközben *látszólag* hatástalanított aknamezőn ugróiskolázott.`,
        `${user} meghalt, miközben Anglia városát próbálta megtalálni`,
        `${user} meghalt. OOF`,
        `${user} meghal, miután lenyel egy fogpiszkálót.`,
        `${user} ${interaction.user} kezei által hal meg.`,
        `${user} meghal, mert egy hajcsattal emelte fel a szempilláit`,
        `${user} meghal, mert egyszerűen túl dühös volt.`,
        `${user} meghal, mert káromkodott egy keresztény Minecraft szerveren`,
        `${user} meghal barátok hiányában.`,
        `${user} meghal a rossz szopás miatt.`,
        `${user} meghal, mert túl erősen dabolt.`,
        `${user} meghal, mert túl erősen dabolt`,
        `${user} meghal, mert tiszteletlen volt a "csajokkal".`,
        `${user} meghal, mert egyszerűen egy rossz, ellenszenves pasas.`,
        `${user} meghal, mert necces mémeket posztolt.`,
        `${user} meghal a homok iránti heves ellenszenvtől. Durva, érdes, irritáló, és mindenhová bejut`,
        `${user} meghal, mert megnézte az Emoji filmet, és élvezte.`,
        `${user} egy szörnyű balesetben hal meg, amit ${interaction.user} tervelt ki.`,
        `${user} meghal a Falon túl, és fehér vándorrá válik`,
        `${user} AIDS-ben hal meg.`,
        `${user} vérhasban hal meg.`,
        `${user} természetes halállal hal meg.`,
        `${user} éhen hal.`,
        `${user} halálsoron hal meg halálos injekcióval, miután meggyilkolta ${interaction.user}-t és a családját.`,
        `${user} meghal, de ne hagyd, hogy ez elvonja a figyelmedet attól, hogy 1998-ban The Undertaker ledobta Mankindet a Hell In A Cell tetejéről, aki 5 métert zuhant át egy kommentátori asztalon`,
        `${user} meghal.`,
        `Egy dulakodás után ${user} megöli ${interaction.user}-t`,
        `${user} eltűnt az univerzumból.`,
        `${user} ivott egy mérgező üdítőt, mielőtt visszahívták volna.`,
        `${user} egy Nokia telefont ejtett az arcára, és széthasította a koponyáját.`,
        `${user} megfulladt a saját könnyeiben.`,
        `${user} túl sok copypastát eszik és felrobban`,
        `${user} leesett egy szikláról Pokémon Go közben. Szép munka, hogy a nyavalyás telefonodba temetted az orrod. :iphone:`,
        `${user} beleesett egy verem dühös feministába.`,
        `${user}-t elüti egy autó.`,
        `${user}-t leszúrja ${interaction.user}`,
        `${user}-be villám csap.`,
        `${user} genocide útra lép, és Sans totálisan lenyomja ${user}-t!`,
        `${user} késes verekedésbe keveredett a pápával. Az egyikük most a pokolban van.`,
        `${user}-re rálépett egy elefánt.`,
        `${user} meghalt, mert túl sok segget evett.`,
        `${user} szélütést kap egy szomorú, nyomorult élet után. Ezután felfalják a macskái.`,
        `${user}-t bűnösnek találták, ideje a kivégzésnek!`,
        `${user} rossz kínai kaját eszik, és a végső árat fizeti meg.`,
        `${user}-t elrabolják az idegenek, és a kormány megöli, hogy eltussolja.`,
        `${user} ${interaction.user} kezei által halt meg.`,
        `${user}-be csokiszirupot fecskendeznek, ami csokoládéból készült emberré mutálja. Miközben részmunkaidőben dolgozik egy bölcsődében, felfalják az éhes babák. :chocolate_bar:`,
        `${user}-t megöli egy nyúl, aminek mérföldekre nyúlik a vad hajlama`,
        `${user}-t a saját hülyesége öli meg.`,
        `${user} egy balul sikerült rablás során hal meg.`,
        `${user} nem ölhető meg. Ó, várjunk, mégis, ${interaction.user} megöli mindenképp.`,
        `${user} olyan hülye, hogy megfulladt az oxigéntől.`,
        `${user}-t Freddy egy jelmezbe gyömöszöli az éjszakai őrszolgálata alatt. Ó, ne már megint azok az animatronikok!`,
        `${user}-t beszippantja a Minecraft. ${user}, mivel kezdő az úgynevezett Valós Életbeli Minecraftban, szembesül a Game Over képernyővel.`,
        `${user} megölte magát, miután meglátta a necces mémeket, amiket ${interaction.user} posztol.`,
        `${user} megölte magát, miután rájött, milyen hülye ${interaction.user}.`,
        `${user} életben marad, ${interaction.user} gyilkossági kísérlete ellenére.`,
        `${user} elveszti az élni akarását`,
        `${user} megnyom egy véletlenszerű gombot, és 100 méter magasba teleportálódik, ami elkerülhetetlen halálos zuhanáshoz vezet. A történet tanulsága: ne nyomogass véletlenszerű gombokat.`,
        `${user} addig olvas mémeket, amíg bele nem hal.`,
        `${user} kitépte a szívét..`,
        `${user} kitépte a saját szívét, hogy megmutassa a szerelmét ${interaction.user} iránt.`,
        `${user} rémülten sikít, amikor véletlenül megidézi Cthulhut, miközben véletlenszerű latin szavakat mormol. Cthulhu megragadja ${user} jobb lábát, és elviszi a saját dimenziójába, közben kiabálva: \`Édesem, kész a vacsora!\``,
        `${user} elcsúszott a fürdőszobában, és megfulladt a zuhanyfüggönyön.`,
        `${user} elcsúszik egy banánhéjon, és leesik a lépcsőn.`,
        `${user} megpörget egy fidget spinnert, és amikor az megáll, meghal...`,
        `${user} rálép egy George Foreman grillre, és gofrilábban hal meg.`,
        `${user} nyilat kap a térdébe. És mindenhová máshová is.`,
        `${user} visszapofázott a moderátoroknak, és eltörölte őt a ban kalapács.`,
        `${user} túl messzire billenti a kalapját, és leesik a közeledő metró síneire.`,
        `${user} megpróbált ügyeskedni, de véletlenül megvágta magát az ollóval. :scissors:`,
        `${user} megpróbált híres lenni a YouTube-on valami hülyeség élő közvetítésével. Ejtőernyőzés, miközben egy hűtőhöz volt láncolva.`,
        `${user} megpróbálta lehagyni a vonatot, a vonat nyert.`,
        `${user} megpróbálta kiválasztani a szent grált. Rosszul... választott.`,
        `${user} megpróbált az utcán játszani...`,
        `${user} megbotlik a saját cipőfűzőjében és meghal.`,
        `${user} hangosan ellenezte a Clintonékat, majd hirtelen eltűnt.`,
        `${user} Alderaan lakója volt, mielőtt Darth Vader elpusztította a bolygót...`,
        `${user}-t azzal vádolták, hogy ellopta Neptunusz koronáját...`,
        `${user} éppen a Samsung Galaxy Note 7-esét töltötte...`,
        `${user}-t elevenen felfalták a hangyák`,
        `${user} lehetőséget kapott, hogy szintetizálja a 119-es elemet (Ununennium), és elnevezze magáról, de elszúrta. R.I.P.`,
        `${user}-t ${interaction.user} nedves törlőkendővel ölte meg.`,
        `${user}-t ${interaction.user} gyilkolta meg, és mindenki tudja, de nincs bizonyíték.`,
        `${user}-t kikanalazta ${interaction.user}, és a belsőségei most Ennard.`,
        `${user}-t átteleportálták abba az idővonalba, ahol a Jurassic World valós volt, és elevenen felfalta az Indominus Rex.`,
        `${user}-t ${interaction.user} bedobta egy szemetesautó zúzójába.`,
        `${user} simán sétált, amikor a szeme sarkából meglátott valakit bottle flipet csinálni és dabolni, aminek hatására ${user} szélütést kapott.`,
        `${user} megnézte az Emoji filmet, és a tiszta cringe-tól meghalt.`,
        `${user} elment egy körre egy ólomléggömbbel.`,
        `Miután ${interaction.user} belökte az óceánba, ${user}-t felfalja egy cápa.`,
        `Miután egy sereg Roblox kölyök özönlötte el a szervert, ${user} rákban halt meg.`,
        `Aids, ${user} aidsben halt meg.`,
        `Az isteni erőket megidézve, ${interaction.user} lesújt ${user}-ra és pogány útjaira`,
        `Egy hirtelen fordulattal, **nem** ölöm meg ${user}-t.`,
        `no u`,
        `A mi urunk és megváltónk, Gaben, villámcsapással sújt le ${user}-ra.`,
        `Sajnálom, ${interaction.user}, nem szeretek embereket ölni.`,
        `A golyó elvétette Harambét, és helyette ${user}-t találta el. Éljen Harambe!`,
        `Miközben kolonoszkópiát végzett egy elefánton, ${user} feje beszorult az elefánt végbelébe, és megfulladt.`,
    ];

    client.embed({ title: `🔫・Ölés`, desc: `${kills[Math.floor(Math.random() * kills.length)]}`, type: 'editreply' }, interaction)

}

