
module.exports = async (client, interaction, args) => {

    const user = interaction.options.getUser('user');

    var roasts = [
        "*Betesz a sütőbe.*",
        "Annyira hülye vagy.",
        "Bocsi, nem hallak, túl idegesítő vagy.",
        "Van jobb dolgom is.",
        "Olyan hülye vagy, mint a Cleverbot.",
        "Az IQ-d alacsonyabb, mint a Mariana-árok.",
        "Annyira idegesítő vagy, hogy még a legyek is elkerülik a bűződet.",
        "Kérlek, menj el.",
        "Adnék egy csúnya pillantást, de már van egy arcod.",
        "Úgy néz ki, mintha kigyulladt volna az arcod, és valaki egy kalapáccsal próbálta volna eloltani.",
        "A családfád biztos egy kaktusz, mert mindenki tüske rajta.",
        "Egy nap messzire jutsz, és remélem, ott is maradsz.",
        "Hívott az állatkert. Azon tűnődnek, hogyan szöktél ki a ketrecből.",
        "Egy szellemi párbajra számítottam, de te úgy tűnik, fegyvertelen vagy.",
        "Te vagy a bizonyíték rá, hogy az evolúció visszafelé is haladhat.",
        "Az agy nem minden, a te esetedben pedig egyáltalán nincs is.",
        "Bocsi, nem értettem, nem beszélek hülyéül.",
        "Miért elfogadható, hogy te hülye legyél, de az nem, hogy én ezt szóvá tegyem?",
        "Mindannyian majmoktól származunk, de te nem jutottál elég messzire.",
        "Még a majmok is eljutottak az űrbe, szóval neked egyértelműen hiányzik valami.",
        "Az ész fontosabb az erőnél, neked viszont egyik sincs.",
        "Úgy nézel ki, mint egy majom, és úgy is bűzlesz.",
        "Még a hülyék között is alulteljesítesz.",
        "Még akkor is elbukod, amikor egyáltalán nem csinálsz semmit.",
        "Ha lenne szavazás a 'legkevésbé valószínű, hogy sikeres lesz' kategóriában, te nyernéd az első díjat.",
        "Hülyék vesznek körül... Vagy várjunk, ez csak te vagy.",
        "Haza akarok menni. Illetve inkább csak el akarok szabadulni attól a szörnyű bűztől, amit árasztasz.",
        "Minden alkalommal, amikor hozzám érsz, haza kell mennem, és kilencszer kimosnom minden ruhámat, hogy visszakapjam a normális illatot.",
        "Ha egy dollárt kapnék minden agyért, ami neked nincs, akkor is csak egy dollárom lenne.",
        "Segítenék, hogy sikeres legyél, de te erre képtelen vagy.",
        "A hajvonalad olyan, mint egy grafikon: a pozitív és negatív erők vonzzák egymást, de a hajvágógép és a hajad taszítják.",
        "Tudok egy jó viccet! Te!",
        "Az agyadnak két fele van, 'bal' és 'jobb'. A bal oldalon semmi sincs jól. A jobb oldalon semmi sem maradt.",
        "Féltékeny a segged, mennyi szar jött ki most a szádon?",
        "Nem szállok szellemi párbajba fegyvertelenekkel.",
        "Két rossz nem ad ki egy jót, vedd példának a szüleidet.",
        "A születési anyakönyvi kivonatod egy bocsánatkérő levél az óvszergyártól.",
        "Ésszerűnek hangzol. Biztos ideje felemelni a gyógyszeradagomat!",
        "Biztos az autópályán születtél, mert ott történik a legtöbb baleset.",
        "Olyan csúnya vagy, hogy amikor anyukád leadott az iskolánál, bírságot kapott szemetelésért.",
        "Ha a nevetés a legjobb orvosság, akkor az arcod biztos meggyógyítja a világot.",
        "Szeretném a te szemszögedből látni a dolgokat, de nem tudom ennyire mélyre dugni a fejem a seggembe.",
        "Az egyetlen módja, hogy valaha is szexed legyen, ha bemászol egy csirke seggébe és vársz.",
        "Irigylem azokat, akik sosem találkoztak veled!",
        "Ha nekem is ilyen arcom lenne, beperelném a szüleimet.",
        "Csak egy probléma van az arcoddal. Hogy látom.",
        "Nem szereted a természetet, annak ellenére, amit veled tett?",
        "Milyen nyelven beszélsz? Mert baromságnak hangzik.",
        "A hülyeség nem bűncselekmény, szóval szabadon távozhatsz.",
        "Szóval átfutott egy gondolat az agyadon? Biztos hosszú és magányos út volt.",
        "Szobahőmérsékletű az IQ-d - ha a szoba az Antarktiszon van.",
        "Ha tényleg tudni akarsz a hibákról, kérdezd meg a szüleidet.",
        "Megkérdezném, hány éves vagy, de tudom, nem tudsz addig számolni.",
        "Tudni akarod, honnan van ennyi sértésem? Van egy dolog, amit intelligenciának hívnak.",
        "Adnék egy csúnya pillantást, de már van egy arcod.",
        "Nem tudom, mi a bajod, de fogadok, hogy nehéz kiejteni.",
        "Az agy nem minden. A te esetedben pedig egyáltalán nincs is.",
        "Kívülállóként mit gondolsz az emberi fajról?",
        "Úgy nézel ki, mint egy 'előtte' kép.",
        "Ó, mi? Bocsi. Csak próbáltalak elképzelni személyiséggel.",
        "Miattad kell úszómester a génállományhoz.",
        "Mindig tudjuk, mikor hazudsz. Mozog a szád.",
        "Lehet, hogy szeretek vásárolni, de a baromságodat nem veszem meg.",
        "A pokol a törölt szelfijeiddel van tapétázva.",
        "Élő bizonyítéka vagy, hogy a trágyának is nőhet lába és járhat.",
        "Tudod, hogy a smink nem javítja meg a hülyeségedet, ugye?",
        "Ha hülyének hívnálak, az sértés lenne az összes hülyére nézve.",
        "Tökéletes arcod van a rádiózáshoz.",
        "Áw, de aranyos, amikor olyan dolgokról próbálsz beszélni, amiket nem értesz.",
        "Ha egy seggfejtől akarnék hallani valamit, fingnék egyet.",
        "Mi a különbség közted és egy tojás között? A tojást megtojják!",
        "Úgy nézel ki, mint egy kő, amit homokká zúztak, jointtá sodortak, és egy asztmaspray-n keresztül elszívtak.",
        "A tanácsod annyira hasznos, mint egy papírmasé bombaóvóhely.",
        "Szomorú, hogy a szignód akár 0/0-s is lehetne?",
        "Olyan kövér vagy, hogy tőled a galaxis molekuláris méretűnek tűnik.",
    ];

    client.embed({
        title: `😓・Beégetés`,
        desc: `${user}, ${roasts[Math.floor(Math.random() * roasts.length)]}`,
        type: 'editreply'
    }, interaction)
}

